### ISSUE TITLE
Missing class AppErrorType

### ISSUE THREAD

**Issue by maulikdadhaniya** [almarpa/AndroidBaseTemplate#12]
Here getting error because missing class in code AppErrorType in Extention file
<img width="1242" alt="Screenshot 2024-09-06 at 11 59 19 AM" src="https://github.com/user-attachments/assets/55d1b0a5-a014-4148-afe3-3a8dc243e8c8">

**Comment by almarpa** [comment]
You're right. I'm working on a custom error handler and I missed a class. Today I will update it.
